GET http://localhost:3333/

###
POST http://localhost:3333/create-task
Content-Type: application/json

{
    "nomeFilme": "nome",
    "gênero": "Ação",
    "duração": "120",
    "classificaçãoEtária": "15"
}

###
DELETE http://localhost:3333/create-task/

###
GET http://localhost:3333/completed-tasks

###
GET http://localhost:3333/imcompleted-tasks