GET http://localhost:3333/

###
POST http://localhost:3333/create-filme
Content-Type: application/json

{
    "nomeFilme": "Esqueceram de mim",
    "gênero": "Comédia,Familia",
    "duração": 243,
    "classificaçãoEtária": 10
}

###
DELETE http://localhost:3333/delete-filme/

###
PUT http://localhost:3333/update/14
Content-Type: application/json

{
    "nomeFilme": "Esqueceram de mim",
    "gênero": "Comédia e infantil",
    "duração": 143,
    "classificaçãoEtária": 12
}