GET http://localhost:3333/

###
POST http://localhost:3333/create-filme
Content-Type: application/json

{
    "nomeFilme": "nome",
    "gênero": "Ação",
    "duração": "120",
    "classificaçãoEtária": "15"
}

###
DELETE http://localhost:3333/delete-filme/1

###
GET http://localhost:3333/completed-filme

###
GET http://localhost:3333/imcompleted-filme